import type { TriageCase } from "./types";

/**
 * Fixture set. Narratives deliberately contain (and deliberately omit)
 * protocol trigger phrases so the deterministic bypass is demonstrable.
 */
export const TRIAGE_CASES: readonly TriageCase[] = [
  {
    caseId: "CSE-8841-A",
    patientId: "MRN-40881-XQ",
    initials: "A.R.",
    age: 58,
    sex: "M",
    modality: "ECG",
    aiAssessment: "Non-specific ST changes",
    icd10: "R94.31",
    confidence: 0.94,
    modelStatus: "pending",
    receivedMinutesAgo: 3,
    capturedAt: "14:38:11 UTC",
    sync: "synced",
    syncAttempts: 1,
    narrative:
      "Patient reports chest pain for two hours, describes crushing substernal discomfort radiating to left arm, diaphoretic on arrival.",
    triageNote: "Ambulance handover, aspirin 300mg given pre-hospital.",
    reasoning: [
      "12-lead waveform shows 0.8mm ST depression in V4–V6 without reciprocal elevation.",
      "Model weighted absence of Q waves heavily toward benign repolarisation variant.",
      "Free-text intake channel was NOT part of the vision model's input tensor.",
    ],
    differentials: [
      { label: "Benign early repolarisation", probability: 0.94, icd10: "R94.31" },
      { label: "NSTEMI", probability: 0.041, icd10: "I21.4" },
      { label: "Pericarditis", probability: 0.012, icd10: "I30.9" },
    ],
    vitals: { hr: 104, bp: "148/92", spo2: 96, temp: 37.1, rr: 22 },
    scan: { filename: "ecg_12lead_40881.webp", width: 768, height: 768, quality: 0.82 },
    slaMinutes: 10,
  },
  {
    caseId: "CSE-8840-C",
    patientId: "MRN-40877-LK",
    initials: "M.T.",
    age: 71,
    sex: "F",
    modality: "CT",
    aiAssessment: "Left MCA hypodensity",
    icd10: "I63.512",
    confidence: 0.88,
    modelStatus: "escalated",
    receivedMinutesAgo: 7,
    capturedAt: "14:34:02 UTC",
    sync: "synced",
    syncAttempts: 1,
    narrative:
      "Family noted facial droop and slurred speech beginning approximately 40 minutes before arrival.",
    reasoning: [
      "Loss of grey–white differentiation in the left insular ribbon, ASPECTS estimated 8/10.",
      "No hyperdense vessel sign; haemorrhage probability 0.6%.",
      "Thrombolysis window intact per stated symptom onset.",
    ],
    differentials: [
      { label: "Acute ischaemic stroke, left MCA", probability: 0.881, icd10: "I63.512" },
      { label: "Artefact / beam hardening", probability: 0.072, icd10: "R93.0" },
      { label: "Chronic infarct", probability: 0.031, icd10: "I69.398" },
    ],
    vitals: { hr: 88, bp: "176/98", spo2: 97, temp: 36.8, rr: 18 },
    scan: { filename: "ct_head_nc_40877.webp", width: 768, height: 768, quality: 0.82 },
    slaMinutes: 5,
  },
  {
    caseId: "CSE-8839-B",
    patientId: "MRN-40863-ZP",
    initials: "S.O.",
    age: 34,
    sex: "F",
    modality: "DERM",
    aiAssessment: "Seborrheic keratosis",
    icd10: "L82.1",
    confidence: 0.97,
    modelStatus: "pending",
    receivedMinutesAgo: 12,
    capturedAt: "14:29:47 UTC",
    sync: "offline-recovered",
    syncAttempts: 4,
    narrative:
      "Lesion on right scapula, unchanged for six years per patient, no bleeding or itch.",
    reasoning: [
      "Dermoscopic pattern: milia-like cysts and comedo-like openings, sharply demarcated border.",
      "Asymmetry index 0.11 — well below the 0.34 referral threshold.",
      "Captured offline in clinic 3; queued locally and reconciled after 4 sync attempts.",
    ],
    differentials: [
      { label: "Seborrheic keratosis", probability: 0.968, icd10: "L82.1" },
      { label: "Pigmented BCC", probability: 0.019, icd10: "C44.319" },
      { label: "Melanoma", probability: 0.004, icd10: "C43.9" },
    ],
    vitals: { hr: 72, bp: "118/74", spo2: 99, temp: 36.6, rr: 14 },
    scan: { filename: "derm_scapula_40863.webp", width: 768, height: 768, quality: 0.82 },
    slaMinutes: 240,
  },
  {
    caseId: "CSE-8838-D",
    patientId: "MRN-40851-RT",
    initials: "J.K.",
    age: 46,
    sex: "M",
    modality: "X-RAY",
    aiAssessment: "Right lower lobe consolidation",
    icd10: "J18.1",
    confidence: 0.91,
    modelStatus: "pending",
    receivedMinutesAgo: 18,
    capturedAt: "14:23:10 UTC",
    sync: "synced",
    syncAttempts: 1,
    narrative:
      "Productive cough four days, rigors overnight, febrile and hypotensive at triage, lactate of 3.1.",
    reasoning: [
      "Air bronchograms with silhouetting of the right hemidiaphragm.",
      "No pleural effusion; cardiothoracic ratio within range.",
      "Imaging finding is concordant, but intake text crosses the sepsis bundle threshold.",
    ],
    differentials: [
      { label: "Community-acquired pneumonia", probability: 0.913, icd10: "J18.1" },
      { label: "Aspiration pneumonitis", probability: 0.048, icd10: "J69.0" },
      { label: "Pulmonary infarct", probability: 0.014, icd10: "I26.99" },
    ],
    vitals: { hr: 118, bp: "94/58", spo2: 93, temp: 38.9, rr: 26 },
    scan: { filename: "cxr_pa_40851.webp", width: 768, height: 768, quality: 0.82 },
    slaMinutes: 15,
  },
  {
    caseId: "CSE-8837-A",
    patientId: "MRN-40840-VD",
    initials: "P.N.",
    age: 63,
    sex: "F",
    modality: "FUNDUS",
    aiAssessment: "Moderate NPDR",
    icd10: "E11.339",
    confidence: 0.89,
    modelStatus: "pending",
    receivedMinutesAgo: 26,
    capturedAt: "14:15:38 UTC",
    sync: "degraded",
    syncAttempts: 2,
    narrative:
      "Routine diabetic screening, HbA1c 8.4%, no acute visual complaint reported today.",
    reasoning: [
      "Four microaneurysms per quadrant with two dot-blot haemorrhages, no venous beading.",
      "Macula dry; no evidence of clinically significant macular oedema.",
      "Image gradeable; 11% of field obscured by lens artefact.",
    ],
    differentials: [
      { label: "Moderate NPDR", probability: 0.892, icd10: "E11.339" },
      { label: "Hypertensive retinopathy", probability: 0.081, icd10: "H35.039" },
      { label: "Severe NPDR", probability: 0.021, icd10: "E11.349" },
    ],
    vitals: { hr: 76, bp: "138/84", spo2: 98, temp: 36.7, rr: 16 },
    scan: { filename: "fundus_od_40840.webp", width: 768, height: 768, quality: 0.82 },
    slaMinutes: 1440,
  },
  {
    caseId: "CSE-8836-E",
    patientId: "MRN-40829-HB",
    initials: "D.M.",
    age: 29,
    sex: "M",
    modality: "MRI",
    aiAssessment: "No acute intracranial abnormality",
    icd10: "Z01.89",
    confidence: 0.96,
    modelStatus: "pending",
    receivedMinutesAgo: 41,
    capturedAt: "14:00:22 UTC",
    sync: "offline-recovered",
    syncAttempts: 7,
    narrative:
      "Three-week history of intermittent headache, describes it as the worst headache of my life at onset, now improving.",
    reasoning: [
      "T2/FLAIR sequences unremarkable; no restricted diffusion.",
      "No mass effect, midline shift, or abnormal enhancement.",
      "Sequence set incomplete — GRE/SWI not acquired, limiting blood-product sensitivity.",
    ],
    differentials: [
      { label: "Normal study", probability: 0.961, icd10: "Z01.89" },
      { label: "Migraine without aura", probability: 0.027, icd10: "G43.009" },
      { label: "Subarachnoid haemorrhage", probability: 0.006, icd10: "I60.9" },
    ],
    vitals: { hr: 68, bp: "124/78", spo2: 99, temp: 36.5, rr: 14 },
    scan: { filename: "mri_brain_flair_40829.webp", width: 768, height: 768, quality: 0.82 },
    slaMinutes: 120,
  },
  {
    caseId: "CSE-8835-B",
    patientId: "MRN-40812-WC",
    initials: "L.F.",
    age: 82,
    sex: "F",
    modality: "X-RAY",
    aiAssessment: "Neck of femur fracture",
    icd10: "S72.001A",
    confidence: 0.93,
    modelStatus: "pending",
    receivedMinutesAgo: 55,
    capturedAt: "13:46:55 UTC",
    sync: "synced",
    syncAttempts: 1,
    narrative:
      "Mechanical fall from standing height, external rotation and shortening of the right leg.",
    reasoning: [
      "Cortical discontinuity at the subcapital femoral neck, Garden III appearance.",
      "Shenton's line disrupted; no pelvic ring involvement.",
      "Orthopaedic pathway pre-staged pending your adjudication.",
    ],
    differentials: [
      { label: "Subcapital NOF fracture", probability: 0.934, icd10: "S72.001A" },
      { label: "Pubic ramus fracture", probability: 0.038, icd10: "S32.591A" },
      { label: "Degenerative change only", probability: 0.011, icd10: "M16.11" },
    ],
    vitals: { hr: 84, bp: "132/70", spo2: 96, temp: 36.4, rr: 18 },
    scan: { filename: "xr_pelvis_ap_40812.webp", width: 768, height: 768, quality: 0.82 },
    slaMinutes: 30,
  },
];
